[package]
name = "discounted-zeroone-knapsack"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
rand = { version = "0.8.5", features = ["small_rng"] }
